### ISSUE TITLE
[logic-network] GUI javafx error

### ISSUE THREAD

**Issue by Aditeya** [Aditeya/NineMensMorris#26]
```
...
Exception in thread "Thread-6" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-6
...
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204)
	at com.sun.javafx.scene.control.skin.LabelSkin.handleControlPropertyChanged(LabelSkin.java:49)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$0(BehaviorSkinBase.java:197)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.scene.control.Labeled.setText(Labeled.java:145)
	at ninemensmorris.nmmguisample.NMMGUIBoardThread.run(NMMGUIBoardThread.java:195)
	at java.lang.Thread.run(Thread.java:748)
...
Exception in thread "Thread-6" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-6
coin at G2 = EMPTY
index= 6:2
coin at G3 = EMPTY
index= 7:0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
coin at H1 = EMPTY
index= 7:1
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
coin at H2 = EMPTY
index= 7:2
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
coin at H3 = EMPTY
Creating COn
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:329)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:221)
	at javafx.scene.Parent$1.onChanged(Parent.java:246)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
	at com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:237)
	at com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:103)
Creating Content with componets is bcs
	at javafx.scene.layout.HBox.<init>(HBox.java:249)
	at ninemensmorris.nmmguisample.NMMGUIBoardThread.createContent(NMMGUIBoardThread.java:80)
BCS = [H1, G1, H2, F1, G2, H3, E1, F2, G3, D1, E2, F3, C1, D2, E3, B1, C2, D3, A1, B2, C3, A2, B3, A3]
	at ninemensmorris.nmmguisample.NMMGUIBoardThread.run(NMMGUIBoardThread.java:145)
slot = H1 type =EMPTY pos 100.0
	at java.lang.Thread.run(Thread.java:748)
slot = G1 type =EMPTY pos 200.0
Exception in thread "Thread-6" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-6
slot = H2 type =EMPTY pos 350.0
slot = F1 type =EMPTY pos 300.0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
slot = G2 type =EMPTY pos 350.0
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
slot = H3 type =EMPTY pos 600.0
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
slot = E1 type =EMPTY pos 400.0
slot = F2 type =EMPTY pos 350.0
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:329)
slot = G3 type =EMPTY pos 500.0
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:221)
slot = D1 type =EMPTY pos 100.0
	at javafx.scene.Parent$1.onChanged(Parent.java:246)
slot = E2 type =EMPTY pos 500.0
slot = F3 type =EMPTY pos 400.0
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
slot = C1 type =EMPTY pos 300.0
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
slot = D2 type =EMPTY pos 200.0
slot = E3 type =EMPTY pos 600.0
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
slot = B1 type =EMPTY pos 200.0
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
slot = C2 type =EMPTY pos 350.0
slot = D3 type =EMPTY pos 300.0
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
slot = A1 type =WHITE pos 100.0
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
slot = B2 type =EMPTY pos 350.0
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
slot = C3 type =EMPTY pos 400.0
	at java.util.AbstractList.add(AbstractList.java:108)
slot = A2 type =BLACK pos 350.0
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:209)
slot = B3 type =EMPTY pos 500.0
slot = A3 type =EMPTY pos 600.0
	at ninemensmorris.nmmguisample.NMMGUIBoardThread.createContent(NMMGUIBoardThread.java:88)
	at ninemensmorris.nmmguisample.NMMGUIBoardThread.run(NMMGUIBoardThread.java:145)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-6" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-6
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:329)
	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:221)
	at javafx.scene.Parent$1.onChanged(Parent.java:246)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
	at com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:237)
	at com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:103)
	at ninemensmorris.nmmguisample.NMMGUIBoardThread.createContent(NMMGUIBoardThread.java:90)
	at ninemensmorris.nmmguisample.NMMGUIBoardThread.run(NMMGUIBoardThread.java:145)
	at java.lang.Thread.run(Thread.java:748)
BUILD STOPPED (total time: 52 seconds)
```

happens when when you send a coin from the second player on its first turn

**Comment by EltoCode** [comment]
Fixed by deleting content before adding
